version: '3'
services:
    mongo:
        image: mongo
        container_name: mongoTestDb
        ports:
            - '27017:27017'
        volumes:
            - './.dev/test/data/configdb:/data/configdb'
            - './.dev/test/data/db:/data/db'
    mongo-express:
        image: mongo-express
        container_name: mongo_express
        depends_on:
            - 'mongo'
        ports:
            - '5050:8081'
        environment:
            - 'ME_CONFIG_OPTIONS_EDITORTHEME=ambiance'
