name: .NET Core

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 3.1.101
            - name: Install dependencies
              run: dotnet restore
            - name: Build API
              run: dotnet build ./IOT_DeviceManager.API/IOT_DeviceManager.API.csproj --configuration Release --no-restore
            - name: Build API Test
              run: dotnet build ./IOT_DeviceManager.API/IOT_DeviceManager.API.Test.csproj --configuration Release --no-restore
            - name: Test
              run: dotnet test --no-restore --verbosity normal
